//DATABSE CONSTANTS
export const COMPANY_MODEL = 'COMPANY_MODEL';
export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';

// COMPANY MODULE CONTANTS
export const COMPANY_SERVICE_NAME = 'CompanyService';
export const COMPANY_CREATE_RPC_METHOD = 'CreateCompany';
export const COMPANIES_GET_RPC_METHOD = 'GetCompanies';
export const COMPANY_GET_BYID_RPC_METHOD = 'GetCompany';